export const ResolveErrorCodes = {
  MISSING_NAME: "missing_name",
  NOT_FOUND: "NOT_FOUND",
  UPSTREAM_TIMEOUT: "UPSTREAM_TIMEOUT",
  UPSTREAM_ERROR: "UPSTREAM_ERROR",
  VOUCHER_REQUIRED: "VOUCHER_REQUIRED",
  VOUCHER_INVALID: "VOUCHER_INVALID",
  VOUCHER_NOT_IMPLEMENTED: "VOUCHER_NOT_IMPLEMENTED",
  REGISTRY_DISABLED: "REGISTRY_DISABLED"
} as const;

export type ResolveErrorCode = typeof ResolveErrorCodes[keyof typeof ResolveErrorCodes];
